---
- name: Converge
  hosts: all
  vars_files:
    - vars.yml
  pre_tasks:
    - name: Create rustus user.
      ansible.builtin.user:
        name: "{{ rustus_owner }}"
        state: present
    - name: Create rustus group.
      ansible.builtin.group:
        name: "{{ rustus_group }}"
        state: present
    - name: Pre-create the uploads directory for one of the systemd units.
      # This directory is supposed to keep its owner, group and permissions
      # intact. They will be verified
      #
      ansible.builtin.file:
        path: "{{ existing_dir }}"
        state: directory
        owner: "{{ rustus_owner }}"
        group: root
        mode: "{{ existing_dir_mode }}"
  tasks:
    - name: "Include usegalaxy_eu.rustus"
      ansible.builtin.include_role:
        name: "usegalaxy_eu.rustus"
