---
rustus_version: 0.7.2

rustus_owner: rustus
rustus_group: rustus

rustus_instances:
  - name: uploads
    user: "{{ rustus_owner }}"
    group: "{{ rustus_group }}"
    working_directory: "{{ uploads_dir }}"
    args:
      - --host "127.0.0.1"
      - --port 10081
      - --url "/uploads"
      - --log-level "INFO"
      - "--data-dir {{ uploads_dir }}"

  # Test `working_directory` already existing.
  - name: existing
    user: "{{ rustus_owner }}"
    group: "{{ rustus_group }}"
    working_directory: "{{ existing_dir }}"
    args:
      - --host "127.0.0.1"
      - --port 10082
      - --url "/uploads"
      - --log-level "INFO"
      - "--data-dir {{ existing_dir }}"

uploads_dir: /uploads
existing_dir: /existing
existing_dir_mode: "0774"
